server:
  port: 3344

spring:
  application:
    name: cloud-config-center    #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:zzyybs/springcloud-config.git
          uri: https://github.com/liucuiyun/springcloud-config    #gitHub上面git仓库名称
          #搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/