server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:    #服务的整合处理
        input:    #这个名字是一个通道的名称
          destination: studyExchange    #表示要使用的Exchange名称定义
          content-type: application/json    #设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit    #设置要绑定的消息服务的具体设置
          group: yunA    #加了group会自动持久化

eureka:
  client:    #客户端进行eureka注册的配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2    #设置心跳时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5    #eureka server从上一次收到client心跳之后，等待下一次心跳的超时时间（默认90秒）
    instance-id: receive-8802.com    #在信息列表时显示主机名称
    prefer-ip-address: true    #访问的路径变为ip地址